import {
  SignInButton,
  SignOutButton,
  UserProfile,
  useUser,
} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center gap-2 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {!isLoaded && <p className="text-5xl text-white">Loading...</p>}
        {isLoaded && !isSignedIn && (
          <div className="w-48">
            <SignInButton mode="modal">
              <button className="w-full rounded-3xl bg-white p-4 text-xl font-bold">
                Sign In
              </button>
            </SignInButton>
          </div>
        )}
        {isSignedIn && (
          <div className="flex flex-col gap-4 p-10">
            <UserProfile />
            <SignOutButton>
              <button className="w-full rounded-3xl bg-white p-4 text-xl font-bold">
                Sign Out
              </button>
            </SignOutButton>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
